# Generated by Django 5.2 on 2025-06-09 19:08

import wishlist.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_userext_description_userext_names_day_importantdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userext',
            name='dob',
            field=wishlist.models.MonthDayField(max_length=4, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='userext',
            name='names_day',
            field=wishlist.models.MonthDayField(blank=True, max_length=4, null=True, verbose_name='Names Day'),
        ),
    ]
