# Generated by Django 5.2 on 2025-06-12 17:44

import wishlist.models
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_alter_importantdates_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImportantDates',
            new_name='ImportantDate',
        ),
        migrations.AlterField(
            model_name='userext',
            name='dob',
            field=wishlist.models.MonthDayField(blank=True, max_length=4, null=True, verbose_name='Date of Birth'),
        ),
    ]
