# Generated by Django 5.2 on 2025-09-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_rename_importantdates_importantdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='link_to_shop',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
